// sidebarsGettingStarted.ts
import {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  gettingStartedSidebar: [{type: 'autogenerated', dirName: '.'}],
//   gettingStartedSidebar: [
//     {
//       type: 'doc',
//       id: 'index', // Links to getting-started/index.md or index.mdx
//       label: 'Introduction',
//     },
//     {
//       type: 'category',
//       label: 'Master 1 Guides',
//       items: [{type: 'autogenerated', dirName: 'master1'}], 
//     },
//     {
//       type: 'category',
//       label: 'Master 2 Guides',
//       items: [{type: 'autogenerated', dirName: 'master2'}], 
//     },
//   ],
};

export default sidebars;