import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const mydocSidebars: SidebarsConfig = {
   myDocSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'wide-doc', // Put your document's Front Matter filename or implicit ID here
      ],
    },
  ],
};

export default mydocSidebars;


/*
// Auto-Generate Folder Items
myDocSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Loops through your root docs folder structures automatically
    },
  ],

//Cross-Link a Ref File
myDocSidebar: [
    {
      type: 'ref',
      id: 'wide-doc', // Shares layout binding constraints without breaking directory rules
    },
  ],
  
*/